In [72]:
# a first run through implementing a phylo HMM
import numpy as np

import Bio
from Bio import HMM
from Bio import Phylo

from hmmlearn import hmm


# set up an example HMM

testModel = hmm.MultinomialHMM(n_components=3)
testModel.startprob_ = 1./0.9 * np.array([0.3, 0.3, 0.3])
testModel.transmat_ = 1./0.9 *np.array([[0.3, 0.3, 0.3],
                                 [0.3, 0.3, 0.3],
                                 [0.1, 0.3, 0.5]])

#testModel.means_ = np.array([[0.0, 0.0], [3.0, -3.0], [5.0, 10.0]])
#testModel.covars_ = np.tile(np.identity(2), (3, 1, 1))
testModel.n_features = 4
testModel.emissionprob_ = ( np.ones((3,4)) + np.eye(4)[:-1, :]   )/ 5

#X, Z = testModel.sample(100)  # X is the sequence of emissions, Z is the sequence of states

X = np.array([[2,3,0,1]] ).T
testModel.predict(np.array([[1,2,3,1]] ).T)


array([1, 2, 2, 1])

In [62]:
testModel.emissionprob_

array([[ 0.4,  0.2,  0.2,  0.2],
       [ 0.2,  0.4,  0.2,  0.2],
       [ 0.2,  0.2,  0.4,  0.2]])

In [63]:
testModel.emissionprob_[:, np.concatenate(X)].T

array([[ 0.2,  0.2,  0.4],
       [ 0.2,  0.2,  0.2],
       [ 0.4,  0.2,  0.2],
       [ 0.2,  0.4,  0.2]])

In [64]:
testModel._compute_log_likelihood(X)

array([[-1.60943791, -1.60943791, -0.91629073],
       [-1.60943791, -1.60943791, -1.60943791],
       [-0.91629073, -1.60943791, -1.60943791],
       [-1.60943791, -0.91629073, -1.60943791]])

In [71]:
testModel.transmat_

array([[ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333]])